### PR TITLE
Modified Parser.js to handle new Item Class line 

### PR DESCRIPTION
**Pull request by r-last**
Modified Parser.js to handle new Item Class line added by GGG in POE 3.14

Thanks to @AdVurt for his much more elegant suggestion to solving the problem.

### CODE REVIEW

**Comment by Odzinic** [comment]
Just curious, what did you build this on? I can't seem to get the AppImage for your PR or the master to build at all on Linux.

**Comment by r-last** [comment]
> 
> 
> Just curious, what did you build this on? I can't seem to get the AppImage for your PR or the master to build at all on Linux.

I built this on Windows although I suspect my machine is a little funky. It did take both a `npm install` and `npm audit fix` to get the base code to start before I started working on the code. I only included the javascript changes in the pull as the simple change of one js file should not affect the build process.

**Comment by Odzinic** [comment]
> > Just curious, what did you build this on? I can't seem to get the AppImage for your PR or the master to build at all on Linux.
> 
> I built this on Windows although I suspect my machine is a little funky. It did take both a `npm install` and `npm audit fix` to get the base code to start before I started working on the code. I only included the javascript changes in the pull as the simple change of one js file should not affect the build process.

Glad it works for you. I'm not too experienced with npm to try to figure out why it doesn't build but regardless this isn't something to discuss in a PR it's more for issues. Just wanted to test it out for you on Linux as well.

**Comment by Anupalabdhi** [comment]
Just to follow up on @Odzinic's point (at the risk of going slightly off-topic from this PR), I tried building the original undg's master and r-last's master on linux, but npm kept erroring out in the 'npm install' phase. Now, I am not the technical type, but from what I could gather, it was cranking out on account of the node module "ref" which as I found out hasn't been updated in a while. I tried manually installing ref through npm, and the command moved forward but it threw up [audit warnings](https://ghostbin.co/paste/5hfs8w) about vulnerabilities while doing npm install. The dependencies seem to be in a deprecated mess.

**Comment by roerch** [comment]
Finally managed to build it myself on Linux, but I had to use the --no-audit option of 'npm install', since the audit would replace electron to a new version, which in turn depends on a new version of nodejs itself and for somewhat reason this project doesn't go well with node > v8. It appears that quite some effort would be needed to upgrade this project to the most recent versions of each software package.
EDIT: Just as a follow-up. The changes to the clipboard contents seem to be larger than "just adding a row". Currencies do work, Uniques, Maps, etc. don't.

**Comment by undg** [comment]
https://github.com/undg/xenontrade/releases/tag/v1.2.4

**Pull request merged**
